version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api123
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: DOCKERFILE
      target: development
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://your_username:your_password@postgres:5432/your_database_name
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
